#!/bin/bash

bold=$(tput bold)
normal=$(tput sgr0)

usage()
{
  echo
  echo "Print list of Agile Stacks platform configurations"
  echo "usage: $0"
  echo
  exit 0
}

while [ "$1" != "" ]; do
  case $1 in
    -h | --help )   usage
                    exit
                    ;;
  esac
  shift
done

envdir="$(pwd)/.hub/env"
mappingfile="$envdir/platforms"

mkdir -p "$envdir"
touch "$mappingfile"
platforms=$(<"$mappingfile")

if test -z "$platforms"; then
  platforms="N/A Run ${bold}hub configure -p <KUBE CONTEXT NAME> ${normal}to add"
fi

echo
echo "${bold}List of Agile Stacks platform configurations:${normal}"
echo
echo -e "Kube context name,ASI Platform configuration name\n , \n$platforms" | \
  sed 's/\t/,|,/g' | column -s ',' -t
echo

current=$(readlink .env)
filename=$(basename "$current")
if test -n "$filename"; then
  echo "Current configuration: ${bold}$filename${normal}"
  echo
fi
echo "-----"
echo
echo "${bold}List of Kubernetes cluster contexts (from your local Kubeconfig) \
without Agile Stacks platform configuration:${normal}"
echo

clusters=$(kubectl config get-contexts --output='name')

while IFS= read -r cluster ;
do
  if test -z "$(echo "$platforms" | grep "$cluster")"; then
		  echo "$cluster";
	fi
done <<< "$clusters"
echo
