#!/bin/bash

usage() {
cat << EOF

Deploys Stack Template
Usage: $(basename "$0") [-c]
Parameters:
    -c --components    List of components to deploy
    -o --offset        Deploy starting with the given component

EOF
}

while [ "$1" != "" ]; do
    case $1 in
        -c | --component )      shift
                            COMPONENTS="$1"
                            ;;
        -o | --offset )         shift
                            OFFSET="$1"
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

if [[ ! -f .env ]]; then
  echo -e "Configuration has not been found. Run 'hub configure'"
  exit 1
fi
# shellcheck disable=SC1091
source .env

echo
echo "Deploying platform $PLATFORM_NAME.$BASE_DOMAIN"
echo

hub ext cloud

make elaborate
if [[ -n "$COMPONENTS" ]]; then
  make deploy COMPONENT="$COMPONENTS"
elif [[ -n "$OFFSET" ]]; then
  make deploy OFFSET="$OFFSET"
else
  make deploy
fi
