#!/bin/bash

DOMAIN_NAME="$PLATFORM_NAME.$BASE_DOMAIN"
CURRENT=$(kubectl config current-context)
echo -e "\nDeleting current local kubeconfig file, if exists"
rm -r ./kubeconfig
echo -e "\nUsing $CURRENT context from system's kubeconfig to provision the platform"
echo -e "\n------------------------------------------------------------------------"
kubectl config view --minify --flatten > kubeconfig
sed -ie "s/  name: $CURRENT/  name: $DOMAIN_NAME/" kubeconfig
sed -ie "s/current-context: $CURRENT/current-context: $DOMAIN_NAME/" kubeconfig
