#!/bin/bash

usage() {
cat << EOF
Undeploys Stack Template
Usage: $(basename "$0") [-c]
Parameters:
    -c --components    List of components to deploy
    -o --offset        Deploy starting with the given component
EOF
}

while [ "$1" != "" ]; do
    case $1 in
        -c | --component )      shift
                            COMPONENTS="$1"
                            ;;
        -o | --offset )         shift
                            OFFSET="$1"
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

if [[ ! -f .env ]]; then
  echo -e "Configuration has not been found. Run 'hub configure'"
  exit 1
fi
source .env

echo "  ____                        _           _      _       ";
echo " / ___| _   _ _ __   ___ _ __| |__  _   _| |__  (_) ___  ";
echo " \___ \| | | | '_ \ / _ \ '__| '_ \| | | | '_ \ | |/ _ \ ";
echo "  ___) | |_| | |_) |  __/ |  | | | | |_| | |_) || | (_) |";
echo " |____/ \__,_| .__/ \___|_|  |_| |_|\__,_|_.__(_)_|\___/ ";
echo "             |_|                                         ";
echo -e "\n------------------------------------------------------------------------"
echo -e "\nUndeploying platform : $PLATFORM_NAME.$BASE_DOMAIN"
echo -e "\n------------------------------------------------------------------------"

hub ext cloud

hub ext kubeconfig
KUBECONFIG="$(pwd)/kubeconfig"
export KUBECONFIG

make elaborate
if [[ -n "$COMPONENTS" ]]; then
  make undeploy COMPONENT="$COMPONENTS"
elif [[ -n "$OFFSET" ]]; then
  make undeploy OFFSET="$OFFSET"
else
  make undeploy
fi